platform: linux

image_resource:
  type: docker-image
  source:
    repository: gradle

inputs:
- name: source_code

outputs:
- name: built-project

run:
  path: sh
  args:
  - -exc
  - |
    cd source_code
    mvn package
    cp ./target/gs-spring-boot-0.0.1-SNAPSHOT.jar ../built-project/demo.jar