platform: linux

image_resource:
  type: docker-image
  source:
    repository: gradle

inputs:
- name: source_code

outputs:
- name: built-project

run:
  user: root
  path: sh
  args:
  - -exc
  - |
    cd source_code
    gradle --stacktrace build
    fly hijack
    cp /tmp/build/put/built-project/demo.jar
    
