platform: linux

image_resource:
  type: docker-image
  source:
    repository: gradle

inputs:
- name: source_code

outputs:
- name: built-project

run:
  user: root
  path: sh
  args:
  - -exc
  - |
    gradle --stacktrace build
    gradle clean assemble
    pwd
    ls
    cd source_code
    ls
    cp  build/libs/*.jar ../artifacts
