platform: linux

image_resource:
  type: docker-image
  source:
    repository: gradle

inputs:
- name: source_code

outputs:
- name: built-project

run:
  user: root
  path: sh
  args:
  - -exc
  - |
    cd source_code
    cd complete
    gradle --stacktrace build
    cd ..
    pwd
    cd ..
    pwd
    cd ..
    cp ./80754af9/source_code/complete/build/libs/gs-spring-boot-0.1.0.jar /tmp/build/put/built-project/demo.jar
    pwd 
    ls
    
    
    
    
