resources:
- name: source_code
  type: git
  source:
    uri: https://github.com/brooklyyounce/gs-spring-boot.git
    
- name: deploy_cf
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: younceb@goldmail.etsu.edu
    password: Brookly likes the number 47.
    organization: younceb-org
    space: development


jobs:
- name: deploy-to-cf-job
  serial: true
  plan:
  - {get: source_code/complete, trigger: true}
  - task: build
    privileged: true
    file: source_code/complete/build.yml
  - put: deploy_cf
    params:
      manifest: source_code/complete/manifest.yml
      path: built-project/demo.jar
